export type Lang = "id" | "en";

export interface Translations {
  // Header
  agentOnline: string;
  brandName: string;

  // Welcome message (Luna)
  welcomeMessage: string;

  // Input
  inputPlaceholder: string;
  attachFile: string;

  // Disclaimer
  disclaimer: string;

  // Chat labels
  you: string;
  aiLabel: string;

  // Searching indicator
  searchingLabel: string;
  searchingText: (query: string) => string;

  // Quick Prompts (fallback)
  quickPrompts: {
    gaming: {
      title: string;
      description: string;
      prompt: string;
    };
    flagship: {
      title: string;
      description: string;
      prompt: string;
    };
  };

  // Error messages
  connectionError: string;

  // Language toggle
  langToggleLabel: string;

  // Product Card Buttons
  checkStockBtn: string;
  detailBtn: string;
  bookingBtn: string;

  // Prompts generated by actions
  checkStockPrompt: (productName: string) => string;
  viewSpecsPrompt: (productName: string) => string;
  bookingPrompt: (productName: string) => string;

  // Help Modal Bilingual
  helpTitle: string;
  helpIntro: string;
  helpClose: string;
  helpFeatures: {
    rec: { title: string; desc: string };
    card: { title: string; desc: string };
    search: { title: string; desc: string };
    book: { title: string; desc: string };
  };
}

const id: Translations = {
  // Header
  agentOnline: "Agent Online",
  brandName: "AIMER FUTURE",

  // Welcome message
  welcomeMessage:
    "Halo! Saya Luna, konsultan smartphone toko Aimer. 👋\n\nSaya siap bantu kamu cari gadget terbaik sesuai kebutuhan dan budgetmu! Semua rekomendasi saya selalu berdasarkan produk yang tersedia di toko kita, jadi gak perlu khawatir soal keakuratan datanya ya 😊\n\nMau cari HP apa hari ini?",

  // Input
  inputPlaceholder: "Tanyakan seputar smartphone...",
  attachFile: "Lampirkan File",

  // Disclaimer
  disclaimer:
    "Sistem AI dapat melakukan kesalahan. Harap verifikasi informasi penting secara mandiri.",

  // Chat labels
  you: "Anda",
  aiLabel: "AIMER AGENT",

  // Searching indicator
  searchingLabel: "Penelusuran Web",
  searchingText: (query) => `Mencari "${query}" di internet...`,

  // Quick Prompts
  quickPrompts: {
    gaming: {
      title: "Rekomendasi HP Gaming",
      description:
        "Cari smartphone performa tinggi untuk gaming budget di bawah 5 juta.",
      prompt:
        "Bisa rekomendasikan smartphone untuk gaming dengan budget di bawah 5 juta?",
    },
    flagship: {
      title: "Bandingkan Flagship",
      description:
        "Perbandingan spesifikasi antara iPhone 15 Pro dan Samsung Galaxy S24 Ultra.",
      prompt:
        "Apa perbedaan spesifikasi dan keunggulan antara iPhone 15 Pro dengan Samsung Galaxy S24 Ultra?",
    },
  },

  // Error
  connectionError: "Koneksi ke sistem **Aimer Agent** gagal. Coba lagi dalam beberapa saat.",

  // Language toggle
  langToggleLabel: "EN",

  // Product Card Buttons
  checkStockBtn: "Tanya Stok",
  detailBtn: "Detail",
  bookingBtn: "Booking Sekarang",

  // Prompts generated by actions
  checkStockPrompt: (productName) => `Apakah unit **${productName}** saat ini ready stock di toko Anda?`,
  viewSpecsPrompt: (productName) => `Bisa tolong berikan rincian spesifikasi lengkap dan kelebihan dari **${productName}**?`,
  bookingPrompt: (productName) => `Bisa tolong booking produk **${productName}** untuk saya?`,

  // Help Modal Bilingual
  helpTitle: "Aimer Agent — Panduan Penggunaan",
  helpIntro: "Halo! Saya Luna, asisten AI Anda. Berikut adalah panduan singkat cara berinteraksi dengan asisten pintar kami:",
  helpClose: "Mengerti, Tutup Panduan",
  helpFeatures: {
    rec: {
      title: "Konsultasi & Rekomendasi Gadget",
      desc: "Tanyakan HP terbaik berdasarkan budget, kamera, gaming, atau merek tertentu. Contoh: 'Rekomendasi HP gaming budget 3 juta' atau 'Bandingkan Samsung S24 dengan iPhone 15'."
    },
    card: {
      title: "Kartu Produk Interaktif",
      desc: "AI akan menampilkan kartu spesifikasi produk interaktif di chat. Cukup klik tombol 'Tanya Stok', 'Detail', atau 'Booking' pada kartu tersebut untuk aksi instan."
    },
    search: {
      title: "Penelusuran Web & Benchmark",
      desc: "Luna dapat melakukan pencarian data eksternal di internet secara real-time seperti skor Antutu, Geekbench, review ahli, dan menyertakan sitasi sumber terpercaya."
    },
    book: {
      title: "Sistem Booking WhatsApp Otomatis",
      desc: "Katakan 'Tolong booking Infinix GT 20 Pro'. Cukup sebutkan Nama Lengkap & nomor WhatsApp aktif Anda, maka bukti reservasi dan kode booking akan otomatis terkirim ke WhatsApp Anda!"
    }
  }
};

const en: Translations = {
  // Header
  agentOnline: "Agent Online",
  brandName: "AIMER FUTURE",

  // Welcome message
  welcomeMessage:
    "Hello! I'm Luna, Aimer store's smartphone consultant. 👋\n\nI'm ready to help you find the best gadget that fits your needs and budget! All my recommendations are always based on products available in our store, so no need to worry about data accuracy 😊\n\nWhat phone are you looking for today?",

  // Input
  inputPlaceholder: "Ask about smartphones...",
  attachFile: "Attach File",

  // Disclaimer
  disclaimer:
    "AI systems can make mistakes. Please verify important information independently.",

  // Chat labels
  you: "You",
  aiLabel: "AIMER AGENT",

  // Searching indicator
  searchingLabel: "Web Search",
  searchingText: (query) => `Searching "${query}" on the internet...`,

  // Quick Prompts
  quickPrompts: {
    gaming: {
      title: "Gaming Phone Picks",
      description:
        "Find high-performance smartphones for gaming under 5 million IDR.",
      prompt:
        "Can you recommend a smartphone for gaming with a budget under 5 million IDR?",
    },
    flagship: {
      title: "Compare Flagships",
      description:
        "Compare specs between iPhone 15 Pro and Samsung Galaxy S24 Ultra.",
      prompt:
        "What are the spec differences and advantages between iPhone 15 Pro and Samsung Galaxy S24 Ultra?",
    },
  },

  // Error
  connectionError: "Connection to **Aimer Agent** failed. Please try again in a moment.",

  // Language toggle
  langToggleLabel: "ID",

  // Product Card Buttons
  checkStockBtn: "Check Stock",
  detailBtn: "Detail",
  bookingBtn: "Book Now",

  // Prompts generated by actions
  checkStockPrompt: (productName) => `Is the **${productName}** unit currently in stock at your store?`,
  viewSpecsPrompt: (productName) => `Could you please provide the full specifications and advantages of **${productName}**?`,
  bookingPrompt: (productName) => `Could you please book the **${productName}** product for me?`,

  // Help Modal Bilingual
  helpTitle: "Aimer Agent — Usage Guide",
  helpIntro: "Hello! I'm Luna, your AI smartphone assistant. Here is a quick guide on how to interact with our smart agent:",
  helpClose: "Got it, Close Guide",
  helpFeatures: {
    rec: {
      title: "Gadget Consultation & Recommendations",
      desc: "Ask for the best smartphone based on your budget, camera, gaming needs, or specific brands. Example: 'Gaming phone recommendation budget 3 million' or 'Compare Samsung S24 with iPhone 15'."
    },
    card: {
      title: "Interactive Product Cards",
      desc: "The AI will display rich product specification cards in the chat. Simply click 'Check Stock', 'Detail', or 'Book Now' on the card for instant actions."
    },
    search: {
      title: "Web Search & Benchmarks",
      desc: "Luna can search the internet in real-time for external specs, Antutu/Geekbench scores, and expert reviews, along with professional citations."
    },
    book: {
      title: "Automated WhatsApp Booking System",
      desc: "Say 'Please book Infinix GT 20 Pro'. Once you provide your Full Name & active WhatsApp number, a reservation code and booking receipt will automatically be sent to your WhatsApp!"
    }
  }
};

export const translations: Record<Lang, Translations> = { id, en };
