export type Lang = "id" | "en";

export interface Translations {
  // Header
  agentOnline: string;
  brandName: string;

  // Welcome message (Lina)
  welcomeMessage: string;

  // Input
  inputPlaceholder: string;
  attachFile: string;

  // Disclaimer
  disclaimer: string;

  // Chat labels
  you: string;
  aiLabel: string;
  aiHeader: string;

  // Searching indicator
  searchingLabel: string;
  searchingText: (query: string) => string;

  // Quick Prompts (fallback)
  quickPrompts: {
    gaming: {
      title: string;
      description: string;
      prompt: string;
    };
    compare: {
      title: string;
      description: string;
      prompt: string;
    };
    audio: {
      title: string;
      description: string;
      prompt: string;
    };
    power: {
      title: string;
      description: string;
      prompt: string;
    };
  };

  // Error messages
  connectionError: string;

  // Language toggle
  langToggleLabel: string;

  // Product Card Buttons
  checkStockBtn: string;
  detailBtn: string;
  bookingBtn: string;

  // Prompts generated by actions
  checkStockPrompt: (productName: string) => string;
  viewSpecsPrompt: (productName: string) => string;
  bookingPrompt: (productName: string) => string;

  // Help Modal Bilingual
  helpTitle: string;
  helpIntro: string;
  helpClose: string;
  helpFeatures: {
    rec: { title: string; desc: string };
    card: { title: string; desc: string };
    search: { title: string; desc: string };
    book: { title: string; desc: string };
  };
  loginBtn: string;
  registerBtn: string;
  logoutBtn: string;
  loginTitle: string;
  registerTitle: string;
  emailLabel: string;
  passwordLabel: string;
  nameLabel: string;
  phoneLabel: string;
  submitLogin: string;
  submitRegister: string;
  switchToRegister: string;
  switchToLogin: string;
  authSuccessMessage: string;
  registerSuccessMessage: string;
  orDivider: string;
  landing: {
    slogan: string;
    subSlogan: string;
    description: string;
    startBtn: string;
    featuresTitle: string;
    feature1Title: string;
    feature1Desc: string;
    feature2Title: string;
    feature2Desc: string;
    feature3Title: string;
    feature3Desc: string;
    quickStartTitle: string;
    resetLandingBtn: string;
  };
}

const id: Translations = {
  // Header
  agentOnline: "Agent Online",
  brandName: "AIMER FUTURE",

  // Welcome message
  welcomeMessage:
    "Halo! Lina di sini, konsultan gadget & aksesoris toko Aimer. 👋\n\nLina siap bantu kamu cari gadget dan aksesoris terbaik sesuai kebutuhan dan budgetmu! Mulai dari smartphone, tablet, TWS, charger, casing, antigores, sampai smartwatch — semua rekomendasi lina selalu berdasarkan produk yang tersedia di toko kita 😊\n\nMau cari produk apa hari ini?",

  // Input
  inputPlaceholder: "Tanyakan seputar gadget & aksesoris...",
  attachFile: "Lampirkan File",

  // Disclaimer
  disclaimer:
    "Sistem AI dapat melakukan kesalahan. Harap verifikasi informasi penting secara mandiri.",

  // Chat labels
  you: "Anda",
  aiLabel: "Lina",
  aiHeader: "Lina - Agen AI",

  // Searching indicator
  searchingLabel: "Penelusuran Web",
  searchingText: (query) => `Mencari "${query}" di internet...`,

  // Quick Prompts
  quickPrompts: {
    gaming: {
      title: "HP Gaming Terbaik",
      description:
        "Cari smartphone performa tinggi untuk gaming budget di bawah 5 juta.",
      prompt:
        "Bisa rekomendasikan smartphone untuk gaming dengan budget di bawah 5 juta?",
    },
    compare: {
      title: "Bandingkan Gadget",
      description:
        "Perbandingan spesifikasi antara Samsung Galaxy S24 Ultra dan iPhone 15 Pro.",
      prompt:
        "Apa perbedaan spesifikasi dan keunggulan antara Samsung Galaxy S24 Ultra dengan iPhone 15 Pro?",
    },
    audio: {
      title: "TWS & Audio Murah",
      description:
        "Cari TWS / Earbuds bluetooth terbaik dengan budget di bawah 1 juta.",
      prompt:
        "Rekomendasikan TWS atau earbuds bluetooth dengan kualitas suara bagus di bawah 1 juta rupiah.",
    },
    power: {
      title: "Charger & Powerbank",
      description:
        "Cari charger cepat GaN atau powerbank berkapasitas besar.",
      prompt:
        "Tampilkan rekomendasi charger fast charging GaN dan powerbank yang bagus di toko.",
    },
  },

  // Error
  connectionError: "Koneksi ke sistem **Aimer Agent** gagal. Coba lagi dalam beberapa saat.",

  // Language toggle
  langToggleLabel: "EN",

  // Product Card Buttons
  checkStockBtn: "Tanya Stok",
  detailBtn: "Detail",
  bookingBtn: "Booking Sekarang",

  // Prompts generated by actions
  checkStockPrompt: (productName) => `Apakah unit **${productName}** saat ini ready stock di toko Anda?`,
  viewSpecsPrompt: (productName) => `Bisa tolong berikan rincian spesifikasi lengkap dan kelebihan dari **${productName}**?`,
  bookingPrompt: (productName) => `Bisa tolong booking produk **${productName}** untuk saya?`,

  // Help Modal Bilingual
  helpTitle: "Aimer Agent — Panduan Penggunaan",
  helpIntro: "Halo! Lina di sini, asisten AI gadget & aksesoris Anda. Berikut adalah panduan singkat cara berinteraksi dengan asisten pintar kami:",
  helpClose: "Mengerti, Tutup Panduan",
  helpFeatures: {
    rec: {
      title: "Konsultasi & Rekomendasi Gadget",
      desc: "Tanyakan HP terbaik berdasarkan budget, kamera, gaming, atau merek tertentu. Contoh: 'Rekomendasi HP gaming budget 3 juta' atau 'Bandingkan Samsung S24 dengan iPhone 15'."
    },
    card: {
      title: "Kartu Produk Interaktif",
      desc: "AI akan menampilkan kartu spesifikasi produk interaktif di chat. Cukup klik tombol 'Tanya Stok', 'Detail', atau 'Booking' pada kartu tersebut untuk aksi instan."
    },
    search: {
      title: "Penelusuran Web & Benchmark",
      desc: "Lina dapat melakukan pencarian data eksternal di internet secara real-time seperti skor Antutu, Geekbench, review ahli, dan menyertakan sitasi sumber terpercaya."
    },
    book: {
      title: "Sistem Booking WhatsApp Otomatis",
      desc: "Katakan 'Tolong booking Infinix GT 20 Pro'. Cukup sebutkan Nama Lengkap & nomor WhatsApp aktif Anda, maka bukti reservasi dan kode booking akan otomatis terkirim ke WhatsApp Anda!"
    }
  },
  loginBtn: "Masuk",
  registerBtn: "Daftar",
  logoutBtn: "Keluar",
  loginTitle: "Masuk ke Aimer Future",
  registerTitle: "Daftar Akun Member",
  emailLabel: "Alamat Email",
  passwordLabel: "Kata Sandi",
  nameLabel: "Nama Lengkap",
  phoneLabel: "Nomor WhatsApp",
  submitLogin: "Masuk Sekarang",
  submitRegister: "Daftar & Aktivasi",
  switchToRegister: "Belum punya akun? Daftar gratis di sini",
  switchToLogin: "Sudah punya akun? Masuk di sini",
  authSuccessMessage: "Berhasil masuk! Selamat datang kembali.",
  registerSuccessMessage: "Registrasi sukses! Akun Anda aktif.",
  orDivider: "atau",
  landing: {
    slogan: "Cerdas. Personal. Instan.",
    subSlogan: "Asisten Gadget AI Terbaik untuk Anda",
    description: "Temukan gadget dan aksesoris impian Anda bersama Lina. Dapatkan rekomendasi akurat, cek ketersediaan stok real-time, dan lakukan pemesanan otomatis lewat WhatsApp.",
    startBtn: "Mulai Konsultasi",
    featuresTitle: "Mengapa Memilih Asisten Aimer?",
    feature1Title: "Konsultasi Cerdas",
    feature1Desc: "Rekomendasi HP terbaik sesuai budget, spesifikasi, dan kebutuhan Anda secara akurat.",
    feature2Title: "Cek Stok Real-Time",
    feature2Desc: "Informasi ketersediaan unit langsung dari database toko kami secara instan.",
    feature3Title: "Booking WhatsApp",
    feature3Desc: "Reservasi produk secara otomatis dengan konfirmasi langsung ke nomor WhatsApp Anda.",
    quickStartTitle: "Atau Mulai dengan Topik Berikut:",
    resetLandingBtn: "Panduan Awal"
  }
};

const en: Translations = {
  // Header
  agentOnline: "Agent Online",
  brandName: "AIMER FUTURE",

  // Welcome message
  welcomeMessage:
    "Hello! Lina is here, Aimer store's gadget & accessories consultant. 👋\n\nLina is ready to help you find the best gadgets and accessories that fit your needs and budget! From smartphones, tablets, TWS, chargers, cases, screen protectors, to smartwatches — all recommendations are always based on products available in our store 😊\n\nWhat product are you looking for today?",

  // Input
  inputPlaceholder: "Ask about gadgets & accessories...",
  attachFile: "Attach File",

  // Disclaimer
  disclaimer:
    "AI systems can make mistakes. Please verify important information independently.",

  // Chat labels
  you: "You",
  aiLabel: "Lina",
  aiHeader: "Lina - AI Agent",

  // Searching indicator
  searchingLabel: "Web Search",
  searchingText: (query) => `Searching "${query}" on the internet...`,

  // Quick Prompts
  quickPrompts: {
    gaming: {
      title: "Best Gaming Phones",
      description:
        "Find high-performance smartphones for gaming under 5 million IDR.",
      prompt:
        "Can you recommend a smartphone for gaming with a budget under 5 million IDR?",
    },
    compare: {
      title: "Compare Gadgets",
      description:
        "Compare specs between Samsung Galaxy S24 Ultra and iPhone 15 Pro.",
      prompt:
        "What are the spec differences and advantages between Samsung Galaxy S24 Ultra and iPhone 15 Pro?",
    },
    audio: {
      title: "TWS & Audio Picks",
      description:
        "Find the best bluetooth TWS / Earbuds under 1 million IDR.",
      prompt:
        "Recommend some good sound quality bluetooth TWS or earbuds under 1 million IDR.",
    },
    power: {
      title: "Chargers & Powerbanks",
      description:
        "Find fast-charging GaN chargers or high-capacity powerbanks.",
      prompt:
        "Show some recommendations for fast charging GaN chargers and reliable powerbanks in the store.",
    },
  },

  // Error
  connectionError: "Connection to **Aimer Agent** failed. Please try again in a moment.",

  // Language toggle
  langToggleLabel: "ID",

  // Product Card Buttons
  checkStockBtn: "Check Stock",
  detailBtn: "Detail",
  bookingBtn: "Book Now",

  // Prompts generated by actions
  checkStockPrompt: (productName) => `Is the **${productName}** unit currently in stock at your store?`,
  viewSpecsPrompt: (productName) => `Could you please provide the full specifications and advantages of **${productName}**?`,
  bookingPrompt: (productName) => `Could you please book the **${productName}** product for me?`,

  // Help Modal Bilingual
  helpTitle: "Aimer Agent — Usage Guide",
  helpIntro: "Hello! Lina is here, your AI gadget & accessories assistant. Here is a quick guide on how to interact with our smart agent:",
  helpClose: "Got it, Close Guide",
  helpFeatures: {
    rec: {
      title: "Gadget Consultation & Recommendations",
      desc: "Ask for the best gadget or accessory based on your budget, camera, gaming needs, or specific brands. Example: 'Gaming phone recommendation budget 3 million' or 'Compare Samsung S24 with iPhone 15'."
    },
    card: {
      title: "Interactive Product Cards",
      desc: "The AI will display rich product specification cards in the chat. Simply click 'Check Stock', 'Detail', or 'Book Now' on the card for instant actions."
    },
    search: {
      title: "Web Search & Benchmarks",
      desc: "Lina can search the internet in real-time for external specs, Antutu/Geekbench scores, and expert reviews, along with professional citations."
    },
    book: {
      title: "Automated WhatsApp Booking System",
      desc: "Say 'Please book Infinix GT 20 Pro'. Once you provide your Full Name & active WhatsApp number, a reservation code and booking receipt will automatically be sent to your WhatsApp!"
    }
  },
  loginBtn: "Sign In",
  registerBtn: "Sign Up",
  logoutBtn: "Sign Out",
  loginTitle: "Sign In to Aimer Future",
  registerTitle: "Register Member Account",
  emailLabel: "Email Address",
  passwordLabel: "Password",
  nameLabel: "Full Name",
  phoneLabel: "WhatsApp Number",
  submitLogin: "Sign In Now",
  submitRegister: "Register & Activate",
  switchToRegister: "Don't have an account? Sign up free here",
  switchToLogin: "Already have an account? Sign in here",
  authSuccessMessage: "Successfully signed in! Welcome back.",
  registerSuccessMessage: "Registration successful! Account is active.",
  orDivider: "or",
  landing: {
    slogan: "Smart. Personal. Instant.",
    subSlogan: "Your Ultimate AI Gadget Companion",
    description: "Find your dream gadget with Lina. Get accurate recommendations, check real-time stock availability, and reserve devices instantly through WhatsApp.",
    startBtn: "Start Consultation",
    featuresTitle: "Why Choose Aimer Assistant?",
    feature1Title: "Intelligent Consultation",
    feature1Desc: "Accurate phone recommendations tailored to your budget, specs, and specific needs.",
    feature2Title: "Real-Time Stock Check",
    feature2Desc: "Instant information on product availability directly from our store database.",
    feature3Title: "WhatsApp Booking",
    feature3Desc: "Automatically reserve products with instant confirmation sent to your WhatsApp.",
    quickStartTitle: "Or Start with These Topics:",
    resetLandingBtn: "Intro Guide"
  }
};

export const translations: Record<Lang, Translations> = { id, en };
